Update TikTok.json
OpenTermsArchive/france-declarations pull request #413
Opened 2022-05-17 15:07 UTC by mvidonne

new link for terms of service [](https://www.tiktok.com/legal/terms-of-service-eea?lang=fr)

2022-05-18 08:03 UTC, clementbiron commented
Bonjour Marie-Pierre.

Merci pour cette proposition de mise à jour !

D'après le message en haut des Terms of Service actuel, le document que tu pointes n'est pas encore en application. Il rentrera en vigueur le 16 juin prochain.

![image](https://user-images.githubusercontent.com/364319/168988308-1ae5376a-6224-4421-901f-7bddb70abb07.png)

Je te propose donc de garder cette PR ouverte en attendant cette date.

ps: il faudra la compléter avec [un fichier d'historique](https://github.com/OpenTermsArchive/contrib-declarations/blob/main/CONTRIBUTING.md#document-declaration-history) sur lequel je peux prendre le relais si tu le souhaites (fais moi savoir).

2022-06-20 12:49 UTC, clementbiron requested changes
@mvidonne could you please add the following `TikTok.history.json` file to your PR? This will allow me to merge.

```json
{
  "Terms of Service": [
    {
      "fetch": "https://www.tiktok.com/legal/terms-of-service?lang=fr",
      "select": [
        ".article-wrapper"
      ],
	  "validUntil": "2022-06-07T12:44:00.000Z"
    }
  ]
}
```

2022-06-21 07:41 UTC, mvidonne commented
@clementbiron not sure how to create the TikTok.history.json

2022-06-21 07:56 UTC, clementbiron commented
1. Create a `TikTok.history.json` file
2. Copy and paste the json code that i wrote above
3. Lint file with `npm run lint` 
4. Commit and push your work
5. 🚀

2022-07-01 15:10 UTC, Amustache commented
@clementbiron ✔️

2022-07-11 08:40 UTC, clementbiron requested changes

2022-07-11 08:40 UTC, clementbiron commented on declarations/TikTok.json
>        ]
It is necessary to clean the version ;)
```suggestion
"select": [
        ".article-wrapper"
      ],
      "remove": [
        ".language-selection",
        ".dropdown-title > img"
      ]
```

2022-07-11 13:57 UTC, clementbiron requested changes
`TikTok.json is not properly formatted. Use the lint script to format it correctly.`

2022-07-11 14:12 UTC, Amustache commented
On va y arriver.

Sorry for the delay!

2022-07-11 14:14 UTC, clementbiron approved these changes

2022-07-11 14:14 UTC, merged